# Generated by Django 6.1.1 on 2026-09-08 06:30

import django.db.models.deletion
import trusts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trusts', '0002_trustgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('trust', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_content', to='trusts.trust')),
            ],
            options={
                'permissions': (('add_topic_to_item', 'Add topic to an item'),),
                'default_permissions': ('add', 'read', 'change', 'delete'),
            },
            bases=(trusts.models.ReadonlyFieldsMixin, models.Model),
        ),
    ]
